name: CI

on: push

jobs:
  build:
    name: ğŸ—ï¸ Gradle build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v4
      - name: ğŸ§° Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        # uses: actions/setup-java@v4
        # with:
        #   java-version: 11
        #   distribution: temurin
        #   cache: gradle
      - name: ğŸ§° Install Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '5.2'
      - name: ğŸ—ï¸ Build with Gradle
        run: gradle build
  test:
    needs: build
    name: âœ… Gradle test
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v4
      - name: ğŸ§° Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        # uses: actions/setup-java@v4
        # with:
        #   java-version: 11
        #   distribution: temurin
        #   cache: gradle
      - name: ğŸ§° Install Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '5.2'
      - name: âœ… Test with Gradle
        run: gradle test
