name: CI

on: push

jobs:
  build:
    name: ğŸ—ï¸ Gradle build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v4
      - name: ğŸ§° Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: ğŸ§° Install Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '6.5'
      - name: ğŸ—ï¸ Build with Gradle
        run: ./gradlew build
  test:
    needs: build
    name: âœ… Gradle test
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v4
      - name: ğŸ§° Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: ğŸ§° Install Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '6.5'
      - name: âœ… Test with Gradle
        run: ./gradlew test
