name: CI

on: push

jobs:
  gradle-build:
    name: ğŸ—ï¸ Gradle build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v4
      - name: ğŸ§° Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: gradle
      - name: ğŸ—ï¸ Build with Gradle
        run: ./gradlew build
  gradle-test:
    name: âœ… Gradle test
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v4
      - name: ğŸ§° Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: gradle
      - name: âœ… Test with Gradle
        run: ./gradlew test
  github-release:
    name: ğŸš€ Create GitHub release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - gradle-build
      - gradle-test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v3
      - name: ğŸš€ Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          generate_release_notes: true
  publish-plugin:
    name: ğŸš€ Publish plugin
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - gradle-build
      - gradle-test
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check-out
        uses: actions/checkout@v4
      - name: ğŸ§° Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: gradle
      - name: ğŸ’ª Set Gradle Plugin Plugin portal credentials
        run: |
          mkdir -p ~/.gradle
          touch ~/.gradle/gradle.properties
          echo gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} >> ~/.gradle/gradle.properties
          echo gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} >> ~/.gradle/gradle.properties
      - name: ğŸš€ Publish with Gradle
        run: ./gradlew publishPlugins
